services:
  - type: web
    name: goodly-frontend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /
    branch: master
    envVars:
      - key: ENVIRONMENT
        value: production
